name: CI - Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./NotificationService.sln

      - name: Build the solution
        run: dotnet build "./NotificationService.sln" --configuration Release --no-restore

      - name: Run unit tests
        run: |
          dotnet test "./Notification.Tests/NotificationService.Tests.csproj" \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./NotificationService/Notification.Tests/TestResults/
